### PR TITLE
Added support for C++ and compilation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Bryce-Dixon — CHANGES_REQUESTED** [review]
Thanks for this, I really appreciate the help. The one thing: `typedef` for st_image does not work in C as the `pixel_data` defaults to a size of 1, meaning any image used this way would not have any of its pixel_data read in. Change that back to the `#define` strategy I was using before (it's functionally identical for the end user, just allows for differently sized `pixel_data`s) and I will approve the commits!

**Comment by Bryce-Dixon** [comment]
[Compiling library](https://trello.com/c/7YMleUe4/116-compiling-library)

**Comment by ghost** [comment]
Oh... sorry, my code is on C++ so I didn't test. If I use #define then it wouldn't work. I'll check it out tomorrow.

**Review by Bryce-Dixon — APPROVED** [review]

**Comment by Bryce-Dixon** [comment]
[BUG Some frames get displayed incorrectly](https://trello.com/c/pOwozIoA/115-bug-some-frames-get-displayed-incorrectly)

**Comment by Bryce-Dixon** [comment]
[Add C++ support](https://trello.com/c/dpjfuVys/114-add-c-support)

**Pull request merged**
